language: node_js
node_js:
  - 8.9.1
cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: Lint
      script: npm run lint
    - stage: Test
      script: npm run test
    - stage: npm release
      install: true # disable automatic npm install
      script: true # disable automatic npm test
      deploy:
        provider: npm
        email:
          secure: "bM/pfiQCHSdpS2xzcuIcx64ZoCUutEo6x+jxpsLSv6T5FVrrs87kOppVo5Xj5uCyC7eDujJ9BkZHY8mt39ZMRj8EG47c7/NeSP0EA9+/lK6L/h3zYRqVaBSyp99WYojlaxxUMF+61t8ybkYRgn4qECdOFAwLhoZS8b9tznTNNNMFQhr13xB1JAcMJzeDzen/DOEm9jVp6+PuBPQC/0ZYRxGJ6SuTPWez0R2iurzbLB5PMQ/OKhzUL4lnezOm0P8L8jimTQgToDzJLDZL6gIqpPVZoOYThJS0cf7WLf8YpCVvp5kuvV1+U3v5xhAL95LbDEIM1dPXvwOK3EiczQ+YIpaoP1WKFwntAI96aG2ILKGwrM5LJrw3KIFEvsz8Mw3AEhlGnT19KVKVAMFTBPi5rsGMRvnnb/22I0tcGKGRhKqtlOWaDK9BoLwgi2ofwgzpZtYHsPe98wpneTri/zRrbcMy9C+252VIiLHBB5lAcuDGuJfpV68xP13ZCj+3Z8rToZK1QvUdob8enw6Yw/jYBPWVj63mJ+YD9neQ8+pkDEvZ5ZyvrRO2kK5LF4avjI0Gc5hAg/1dxunQpnJF73b4uxWQEI8JtyZIq9MX6gvWGYnVR+L/zXCspFDf4FXxLwCfSiYIZVxnlV/A/iMvNwflK4aj2+lHpjuo35F/cOKZVi8="
        api_key:
          secure: "NIYGoD4b13Euotc4NDTUuvzJpw1pddWwZhBUYQpRj2asS3Lw03uYNVLSwjgDJxq77IbLyxEbaJJUhZZSzMWB2+ux/fAoi+bqHhUAOSi+KJLsDeV7crKhf0n1PkJlpmg2j+U8quc/LhOSsGxLYn/fu+vTm02bxuQsJ5+QzDkyqDXEak3iKwltWvq9ch8bZvsWy7oBDYWUiTATDvccDZC+QaNqZGdXLl0UqiQBwu55sxyCoWLX9F2XT35117jO7kq4dheoLAKke5FVeEjYp29X6WWwTx9mM4BoGdFZDRbj+Ef94JkI6gVXgWSzkcZrONVej+WJgFTtnK4biUOsJg8vw60i1jiX9oh8rR3BC6j0qqVT6W9JE+qGi45bHoPccH2ICAFXj/PyjfEykdTACpBRybk0xkjww629/zKk754NERtnXuNA+F5dqY2mfLwU2lqJszVWu65aklSOLfPsyOkXYHDBi64wOcwJnOCZhIvxang4oyQNl2w3dazkP6nUCV925AAsQ3upC1W4HJw3Mhb8PTnChfz5S+4D/tku76GTNMdzcobBtBewRbWIwh59SVW0VOkUQle38a9yFobQxXSawhhGa5KEXOzAhu41sYcBxbqM6SefT3Dy2tFDImTfsUSkW/XmJB3YwCAS6hEkS7hKXX3kYy5IBvqFM7oZLupKKSo="
        on:
          tags: true